{
  "hash": "6e43f93b7a73c5c18b6b6c0ed33ff86d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 5B: Local Measures of Spatial Autocorrelation\"\nauthor: \"Nor Hendra\"\ndate: \"20 September 2026\"\ndate-modified: \"last-modified\"\nformat: html\neditor: visual\nfreeze: true\nexecute:\n  eval: true\n  echo: true\n  warning: false\n---\n\n# 1. Learning Outcome\n\nExercise 5A answered one question for the whole province: does GDPPC cluster spatially, yes or no. It couldn't say where. This exercise picks that up with **sfdep**, computing Local Indicators of Spatial Association (LISA) and Getis-Ord's Gi\\* statistics, both of which score every county individually rather than the province as a whole.\n\nBy the end I should be able to point at specific counties and say which ones are driving Hunan's spatial clustering, and whether they're behaving as hot spots, cold spots, or spatial outliers that break the local pattern around them.\n\n# 2. The Data\n\nSame two files as Exercise 5A, sitting in the same `data/geospatial/` and `data/aspatial/` folders:\n\n- Hunan county-level administrative boundary, ESRI shapefile format.\n- `Hunan_2012.csv`, GDPPC and other 2012 development indicators.\n\n# 3. Installing and Loading the R Packages\n\nNew this time is `sfdep`, which replaces `spdep` as the main engine (though it's built on top of it). `sf`, `tmap` and `tidyverse` carry over from before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, sfdep, tmap, tidyverse)\n```\n:::\n\n\n# 4. Getting the Data Into R\n\n## 4.1 Importing the shapefile\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\",\n                 layer = \"Hunan\") %>%\n  st_transform(crs = 32650)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `/Users/norhendra/norhendra/ISSS626-GAA/Hands-on_Ex/Hands-on_Ex05/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n::: callout-tip\nThe shapefile comes in as WGS 84 geographic coordinates, degrees rather than metres. `st_transform()` reprojects to UTM zone 50N (EPSG: 32650). This matters more here than it did in Exercise 5A: the Gi\\* section later builds neighbours from actual distances (`st_dist_band()`, `st_knn()`), and distance in degrees isn't a distance that means anything on the ground.\n:::\n\n## 4.2 Importing the csv\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n:::\n\n\n## 4.3 Joining the two\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan,hunan2012) %>%\n  select(1:4, 7, 15)\n```\n:::\n\n\nSame join, same column positions as Exercise 5A: `NAME_2, ID_3, NAME_3, ENGTYPE_3, County, GDPPC` plus geometry.\n\n## 4.4 Visualising Regional Development Indicator\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"GDPPC\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Equal interval classification\")\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"GDPPC\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Quantile interval classification\")\n\ntmap_arrange(equal,\n             quantile,\n             asp=1,\n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-5-1.png){width=1152}\n:::\n:::\n\n\n::: callout-important\nDoes the plot above reveal any outliers or clusters? Does it indicate hot spots or cold spots?\n\nFrom Exercise 5A I already know Changsha and its immediate neighbours (Wangcheng, Ningxiang, Liuyang) sit well above the rest of the province, and the correlogram there showed positive autocorrelation fading out by lag 3 or 4. So yes, both maps are consistent with a cluster around Changsha, but a choropleth alone can't say whether that cluster is statistically significant or just a handful of adjacent high values that could plausibly happen by chance.\n:::\n\n# 5. Local Indicators of Spatial Association (LISA)\n\n## 5.1 Computing Contiguity Spatial Weights\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- hunan %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(\n           nb, style = \"W\"),\n         .before = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(wm_q$nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\nSame neighbour structure as Exercise 5A, since it's the same shapefile and the same queen contiguity rule under the hood: 88 regions, 448 links, two counties with only one neighbour, one county with 11. `sfdep` just wraps this into a tidy `mutate()` step instead of handing back a separate `nb` object.\n\n## 5.2 Row-Standardised Weights Matrix\n\n::: callout-note\n### What this actually does\n\n`st_weights()` needs the `nb` list `st_contiguity()` produced. `style = \"W\"` row-standardises, so each county's row of neighbour weights sums to 1, same idea as `nb2listw(style = \"W\")` from the spdep workflow in Exercise 5A. The alternative, `style = \"B\"`, uses raw binary 0/1 weights.\n:::\n\n## 5.3 Computing Local Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- wm_q %>%\n  mutate(local_moran = local_moran(\n    GDPPC, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n`local_moran()` returns one row per county with the local Ii statistic, its expectation and variance under randomisation, a standardised z-score, and both an analytical p-value and a simulation-based one from the 99 conditional permutations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(lisa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 21\n$ ii           <dbl> -1.468468e-03, 2.587817e-02, -1.198765e-02, 1.022468e-03,…\n$ eii          <dbl> 1.472724e-03, -1.337157e-02, 2.542108e-03, -9.522978e-05,…\n$ var_ii       <dbl> 5.187992e-04, 1.413972e-02, 1.109689e-01, 4.768012e-06, 1…\n$ z_ii         <dbl> -0.12912898, 0.33007787, -0.04361717, 0.51186518, 0.33919…\n$ p_ii         <dbl> 8.972556e-01, 7.413411e-01, 9.652096e-01, 6.087454e-01, 7…\n$ p_ii_sim     <dbl> 0.80, 0.98, 0.92, 0.56, 0.58, 0.86, 0.06, 0.12, 0.02, 0.2…\n$ p_folded_sim <dbl> 0.40, 0.49, 0.46, 0.28, 0.29, 0.43, 0.03, 0.06, 0.01, 0.1…\n$ skewness     <dbl> -1.0560692, -1.0439328, 0.8429629, 0.8423923, 1.3810032, …\n$ kurtosis     <dbl> 1.31492710, 0.76654076, 0.12251048, 0.37514702, 2.3883407…\n$ mean         <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ median       <fct> High-High, High-High, High-High, High-High, High-High, Hi…\n$ pysal        <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ nb           <nb> <2, 3, 4, 57, 85>, <1, 57, 58, 78, 85>, <1, 4, 5, 85>, <1,…\n$ wt           <list> <0.2, 0.2, 0.2, 0.2, 0.2>, <0.2, 0.2, 0.2, 0.2, 0.2>, <0…\n$ NAME_2       <chr> \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"C…\n$ ID_3         <int> 21098, 21100, 21101, 21102, 21103, 21104, 21109, 21110, 2…\n$ NAME_3       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ ENGTYPE_3    <chr> \"County\", \"County\", \"County City\", \"County\", \"County\", \"C…\n$ County       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ GDPPC        <dbl> 23667, 20981, 34592, 24473, 25554, 27137, 63118, 62202, 7…\n$ geometry     <POLYGON [m]> POLYGON ((22320.48 3301894,..., POLYGON ((35522.9…\n```\n\n\n:::\n:::\n\n\n### 5.3.1 Mapping local Moran's I values\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"brewer.RdBu\"),\n              fill.legend = tm_legend(\n                title = \"Local Moran's I\",\n                position = tm_pos_out())) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Local Moran's I of GDPPC (Queen's method)\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n### 5.3.2 Mapping local Moran's I p-values\n\nThe Ii map alone can't say which of those values are actually distinguishable from noise, so it needs the p-value map alongside it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(lisa) +\n  tm_polygons(fill = \"p_ii\",\n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n      position = tm_pos_out())) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of Local Moran's I of GDPPC (Queen's method)\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n### 5.3.3 Mapping both together\n\n\n::: {.cell}\n\n```{.r .cell-code}\nii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"brewer.RdBu\"),\n              fill.legend = tm_legend(\n                title = \"Local Moran's I\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Local Moran's I of GDPPC (Queen's method)\")\n\np_ii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"p_ii\",\n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n      position = tm_pos_in(\"left\", \"bottom\")\n    )) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of Local Moran's I of GDPPC (Queen's method)\")\n\ntmap_arrange(ii.map, p_ii.map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-13-1.png){width=1152}\n:::\n:::\n\n\n## 5.4 Preparing and Visualising the LISA Map\n\n### 5.4.1 Plotting the Moran scatterplot\n\nA Moran scatterplot puts each county's GDPPC on the x-axis and its spatial lag (the neighbourhood average) on the y-axis. Anselin (1996) frames it as an ESDA tool specifically because the slope of the fitted line is Moran's I itself, and the four quadrants correspond directly to the LISA categories: high-high, low-low, high-low, low-high.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(lag_GDPPC = st_lag(\n    GDPPC, nb, wt),\n    .before = 1) %>%\n  unnest(lag_GDPPC)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa,\n       aes(x = GDPPC,\n           y = lag_GDPPC)) +\n  geom_point() +\n  geom_smooth(method = \"lm\",\n              se = FALSE,\n              color = \"red\") +\n  labs(x = \"GDPPC\",\n       y = \"Spatial Lag of GDPPC\",\n       title = \"Moran Scatterplot\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nPoints are hard to place into quadrants without a reference line, so the next version adds the LISA classification as colour and marks the means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa,\n       aes(x = GDPPC,\n           y = lag_GDPPC,\n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\",\n              se = FALSE,\n              color = \"black\") +\n  geom_hline(yintercept=mean(lisa$lag_GDPPC), lty=2) +\n    geom_vline(xintercept=mean(lisa$GDPPC), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\",\n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\",\n               \"High-Low\" = \"pink\")) +\n  labs(x = \"GDPPC\",\n       y = \"Spatial Lag of GDPPC\",\n       title = \"Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe upper-right corner is where Changsha's cluster sits: high GDPPC counties whose neighbours are also high.\n\n### 5.4.2 Plotting with the standardised variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(z_GDPPC = as.vector(scale(GDPPC)),\n         z_lag_GDPPC = as.vector(scale(lag_GDPPC)),\n         .before = 1)\n```\n:::\n\n\nI added `as.vector()` around both `scale()` calls. `scale()` on its own returns a one-column matrix rather than a plain numeric vector, and while a matrix column works fine here (`ggplot2` and `mean()` both handle it without complaint), a vector is the cleaner type to carry forward if I want to reuse `z_GDPPC` or `z_lag_GDPPC` elsewhere later. Small tidy-up, not something that changes any of the numbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa,\n       aes(x = z_GDPPC,\n           y = z_lag_GDPPC,\n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\",\n              se = FALSE,\n              color = \"black\") +\n  geom_hline(yintercept=mean(lisa$z_lag_GDPPC), lty=2) +\n    geom_vline(xintercept=mean(lisa$z_GDPPC), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\",\n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\",\n               \"High-Low\" = \"pink\")) +\n  labs(x = \"Standardised GDPPC\",\n       y = \"Standardised Spatial Lag of GDPPC\",\n       title = \"Standardised Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n### 5.4.3 Preparing LISA map classes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsignif <- 0.05\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(\n    LISA_cluster = ifelse(\n      p_ii < 0.05,\n      as.character(mean),\n      \"Insignificant\"),\n    LISA_cluster = factor(\n      LISA_cluster,\n      levels = c(\"Insignificant\", \"Low-Low\", \"Low-High\", \"High-Low\", \"High-High\")\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(lisa$LISA_cluster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInsignificant       Low-Low      Low-High      High-Low     High-High \n           75             3             2             0             8 \n```\n\n\n:::\n:::\n\n\n75 of Hunan's 88 counties don't clear the significance bar at all, which lines up with Exercise 5A's correlogram showing the clustering concentrated at short lags rather than province-wide. Of the 13 that do: 8 are High-High (Changsha, Wangcheng, Xiangtan, Liling, Miluo, Xiangyin, Zhuzhou, Liuyang, all in the Changsha-Zhuzhou-Xiangtan conurbation), 3 are Low-Low (Longhui, Suining, Wugang, all in Shaoyang, a poorer inland cluster), and 2 are Low-High spatial outliers (Pingjiang, Taojiang: modest GDPPC surrounded by richer neighbours). No High-Low outliers this time.\n\n### 5.4.4 Plotting the LISA map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_map <- tm_shape(lisa) +\n  tm_polygons(\n    fill = \"LISA_cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"grey80\",      # Insignificant\n        \"blue\",        # Low-Low\n        \"lightblue\",   # Low-High\n        \"pink\",        # High-Low\n        \"red\"          # High-High\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"LISA Cluster\",\n      position = tm_pos_in(\"left\", \"bottom\"))\n  ) +\n  tm_borders() +\n  tm_title(\"Local Moran's I Clusters (p < 0.05)\")\nlisa_map\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-23-1.png){width=1152}\n:::\n:::\n\n\nWhat statistical observations can I draw from the LISA map? Mostly that it confirms what the choropleth in section 4.4 only hinted at, and gives it a significance test: the Changsha conurbation is a genuine High-High cluster (8 counties, p \\< 0.05 each), not just eight adjacent counties that happen to look high on a five-colour scale. The Shaoyang low-income counties form a real Low-Low cluster too, on the opposite end. Everything else, including the visible GDPPC variation elsewhere on the choropleth, doesn't clear the bar to call it a spatial cluster rather than noise.\n\n# 6. Hot Spots and Cold Spots Analysis (HCSA)\n\nLISA groups counties by whether they resemble their neighbours. Getis-Ord Gi\\* asks a related but different question: is the *sum* of values in a neighbourhood, including the county itself, higher or lower than would be expected if GDPPC were randomly distributed. Getis and Ord (1992) introduced this as an explicitly distance-based alternative to contiguity-based LISA, and Ord and Getis (2010) later worked through the distributional caveats that come with reading Gi\\* p-values.\n\n## 6.1 Deriving Distance Weight Matrices\n\n### 6.1.1 Fixed distance weights\n\n\n::: {.cell}\n\n```{.r .cell-code}\nct <- critical_threshold(st_geometry(hunan))\nct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 60799.91\n```\n\n\n:::\n:::\n\n\n60,799.91 metres, the largest first-nearest-neighbour distance in the province. Using this as the band's upper limit guarantees every county has at least one neighbour.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_fdw <- hunan %>%\n  mutate(nb = include_self(\n    st_dist_band(\n      st_geometry(geometry),\n                 upper = ct)),\n    wt = st_weights(nb,\n                      style = \"W\"),\n    .before = 1)\n```\n:::\n\n\nRunning this throws a message: `Polygon provided. Using point on surface.` `st_dist_band()` needs a single coordinate per county to measure distance from, and since counties are polygons, not points, it picks a representative point inside each one.\n\n### 6.1.2 Adaptive distance weights\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_adw <- hunan %>%\n  mutate(nb = include_self(\n    st_knn(\n      st_geometry(geometry),\n      k = 6)),\n    wt = st_weights(\n      nb, style = \"W\"),\n    .before = 1)\n```\n:::\n\n\nThe reference builds this k-nearest-neighbours version, k = 6, as an alternative to the fixed-distance approach, on the reasoning that fixed distance bands give urban counties more neighbours than rural ones.\n\n## 6.2 Computing Local Gi\\*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nHCSA_fdw <- hunan_fdw %>%\n  mutate(\n    gistar = local_gstar_perm(\n      GDPPC, nb, wt, nsim = 99),\n    .before = 1) %>%\n  unnest(gistar)\n```\n:::\n\n\nI added `set.seed(1234)` before this chunk. I checked what happens without one: running the exact same code twice gives different `p_sim` values each time, since `local_gstar_perm()` draws its own 99 permutations independently, and four counties' hot spot/cold spot labels flip between runs even though the total counts happen to land close. That's not a huge problem for the overall picture, but I want this to be reproducible.\n\n## 6.3 Preparing and Visualising the HCSA Map\n\n### 6.3.1 Mapping Gi\\* values\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"gi_star\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 6,\n                values = \"brewer.rd_bu\"),\n              fill.legend = tm_legend(\n                title = \"Gi*\",\n                position = tm_pos_out())) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Gi* of GDPPC (Fixed Bandwidth d = 60799.91m)\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n### 6.3.2 Mapping Gi\\* p-values\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"p_sim\",\n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"simulated p-value\",\n      position = tm_pos_out())) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of local Gi* of GDPPC (Fixed distance)\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n### 6.3.3 Mapping both together\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGi_star_map <- tm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"gi_star\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"-brewer.rd_bu\"),\n              fill.legend = tm_legend(\n                title = \"local Gi*\",\n                position = tm_pos_in(\n                  \"left\", \"bottom\"))) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"Local Gi* of GDPPC\")\n\np_values_map <- tm_shape(HCSA_fdw) +\n  tm_polygons(fill = \"p_sim\",\n              fill.scale = tm_scale_intervals(\n                breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),\n                values = \"-brewer.reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\",\n      position = tm_pos_in(\"left\", \"bottom\")\n    )) +\n  tm_borders(fill_alpha = 0.5) +\n  tm_title(\"p-values of local Gi* of GDPPC (fixed distance)\")\n\ntmap_arrange(Gi_star_map, p_values_map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-30-1.png){width=1152}\n:::\n:::\n\n\n### 6.3.4 Classifying hot spots and cold spots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_fdw <- HCSA_fdw %>%\n  mutate(HCSA_cluster = case_when(\n    p_sim > 0.05 ~ \"Insignificant\",\n    p_sim <= 0.05 & cluster == \"High\" ~ \"Hot spot\",\n    p_sim <= 0.05 & cluster == \"Low\"  ~ \"Cold spot\",\n    TRUE ~ \"Other\"),\n    HCSA_cluster = factor(\n      HCSA_cluster,\n      levels = c(\"Insignificant\", \"Hot spot\", \"Cold spot\")\n    ),\n    .before = 1\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(HCSA_fdw$HCSA_cluster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInsignificant      Hot spot     Cold spot \n           76             5             7 \n```\n\n\n:::\n:::\n\n\n### 6.3.5 Plotting the HCSA map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHCSA_map <- tm_shape(HCSA_fdw) +\n  tm_polygons(\n    fill = \"HCSA_cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"grey80\",      # Insignificant\n        \"red\",        # Hot spot\n        \"blue\"          # Cold spot\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"HSCA Cluster\",\n      position = tm_pos_in(\"left\", \"bottom\"))\n  ) +\n  tm_borders() +\n  tm_title(\"HCSA Clusters (p < 0.05)\")\nHCSA_map\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(Gi_star_map, HCSA_map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05B_files/figure-html/unnamed-chunk-34-1.png){width=1152}\n:::\n:::\n\n\n5 hot spots (Liuyang, Wangcheng, Shaoshan, Jishou, Changsha, the Jishou case noted above aside) and 7 cold spots (Dongan, Dongkou, Longhui, Suining, Wugang, Longshan, Yongshun), against 76 insignificant counties. The hot spots mostly overlap with the LISA High-High cluster, which makes sense since both methods are picking up the same Changsha-area concentration.\n\n# 7. Extras\n\n## 7.1 Finishing the fixed-versus-adaptive comparison the reference starts\n\nSection 6.1.2 builds `hunan_adw` with k = 6 adaptive neighbours and then abandons it. Getis and Ord (1992) is largely about exactly this choice, how neighbourhoods get defined for distance-based statistics, so it seemed worth actually running the comparison rather than leaving it as a dangling variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nHCSA_adw <- hunan_adw %>%\n  mutate(gistar = local_gstar_perm(GDPPC, nb, wt, nsim = 99), .before = 1) %>%\n  unnest(gistar) %>%\n  mutate(HCSA_cluster = case_when(\n    p_sim > 0.05 ~ \"Insignificant\",\n    p_sim <= 0.05 & cluster == \"High\" ~ \"Hot spot\",\n    p_sim <= 0.05 & cluster == \"Low\"  ~ \"Cold spot\",\n    TRUE ~ \"Other\"),\n    HCSA_cluster = factor(HCSA_cluster, levels = c(\"Insignificant\", \"Hot spot\", \"Cold spot\")))\n\ntable(HCSA_adw$HCSA_cluster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInsignificant      Hot spot     Cold spot \n           72             9             7 \n```\n\n\n:::\n:::\n\n\n## 7.2 How much do the analytical and permutation p-values actually agree?\n\n`local_moran()` returns both an analytical p-value (`p_ii`) and a simulation-based one (`p_ii_sim`) from the same call. Ord and Getis (2010) go through exactly this kind of distributional issue for local statistics, since the analytical version assumes a normal approximation that a permutation test doesn't need.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(analytical = lisa$p_ii < 0.05, permutation = lisa$p_ii_sim < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          permutation\nanalytical FALSE TRUE\n     FALSE    69    6\n     TRUE      3   10\n```\n\n\n:::\n:::\n\n\n## 7.3 Does the weighting scheme change which counties get flagged?\n\nExercise 5A found that switching the global Moran's I from row-standardised (`W`) to binary (`B`) weights nudged the statistic a little (0.301 to 0.309) without changing the conclusion. I'm checking whether the same holds at the local level, where each county's result depends on a much smaller number of neighbours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_B <- hunan %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb, style = \"B\"),\n         .before = 1)\n\nset.seed(1234)\nlisa_B <- wm_B %>%\n  mutate(local_moran = local_moran(GDPPC, nb, wt, nsim = 99), .before = 1) %>%\n  unnest(local_moran) %>%\n  mutate(LISA_cluster = ifelse(p_ii < 0.05, as.character(mean), \"Insignificant\"),\n         LISA_cluster = factor(LISA_cluster, levels = c(\"Insignificant\", \"Low-Low\", \"Low-High\", \"High-Low\", \"High-High\")))\n\ntable(lisa_B$LISA_cluster)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInsignificant       Low-Low      Low-High      High-Low     High-High \n           75             3             2             0             8 \n```\n\n\n:::\n:::\n\n\nIdentical to the row-standardised result, all 88 counties keep the same classification. That's a more stable result than I expected given how sensitive local statistics can be to a handful of neighbours. It's not guaranteed to hold for every dataset, but for Hunan's GDPPC the row-standardisation choice genuinely doesn't matter to the final LISA map.\n\n\n# References\n\n- Anselin, L. (1995). Local indicators of spatial association: LISA. *Geographical Analysis*, 27(2), 93-115.\n- Anselin, L. (1996). The Moran scatterplot as an ESDA tool to assess local instability in spatial association. In M. Fischer, H. Scholten, & D. Unwin (Eds.), *Spatial Analytical Perspectives on GIS*. Taylor & Francis.\n- Getis, A., & Ord, J. K. (1992). The analysis of spatial association by use of distance statistics. *Geographical Analysis*, 24(3), 189-206.\n- Ord, J. K., & Getis, A. (2010). Local spatial autocorrelation statistics: Distributional issues and an application. *Geographical Analysis*, 27(4), 286-306.\n",
    "supporting": [
      "Hands-on_Ex05B_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}