{
  "hash": "b6342e9af383bee6abef8d5c2d3c7009",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 1A: Geospatial Data Science with R\"\nformat: html\nauthor: \"Nor Hendra\"\ndate: \"23 August 2026\"\neditor: visual\nfreeze: true\nexecute:\n  eval: true\n  echo: true\n  warning: false\n---\n\n# 1. Learning Outcome\n\nGeospatial Data Science is the process of importing, wrangling, integrating, and processing geographically referenced data sets. In this hands-on exercise, I learned how to perform geospatial data science tasks in R by using the **sf** package.\n\nBy the end of this exercise, I acquired the following competencies:\n\n- installing and loading [sf](https://r-spatial.github.io/sf/) and [tidyverse](https://www.tidyverse.org/) packages into the R environment,\n- importing geospatial data by using appropriate functions of the **sf** package,\n- importing aspatial data by using appropriate functions of the **readr** package,\n- exploring the content of a simple feature data frame by using appropriate **Base R** and **sf** functions,\n- assigning or transforming coordinate systems by using appropriate **sf** functions,\n- converting aspatial data into an sf data frame by using appropriate functions of the **sf** package,\n- performing geoprocessing tasks by using appropriate functions of the **sf** package,\n- performing data wrangling tasks by using appropriate functions of the **dplyr** package, and\n- performing Exploratory Data Analysis (EDA) by using appropriate functions from the **ggplot2** package.\n\n::: callout-note\nI made it a habit to read the reference guide of each function, especially the input data requirements, syntax, and argument options, before using them.\n:::\n\n::: callout-important\n## Note on data formats used in this write-up\n\nThe reference material describes the subzone boundary and cycling path as ESRI shapefiles and the pre-school locations as a KML. What I actually downloaded from data.gov.sg and LTA DataMall came as **GeoJSON** for all three geospatial layers instead. I adapted the code and the explanation accordingly, and flagged every place this changes something.\n:::\n\n# 2. Data Acquisition\n\nData are key to any form of analytics, geospatial analytics included. Before analysing, the necessary data must first be assembled. For this exercise, I extracted the following data sets:\n\n- Master Plan 2014 Subzone Boundary (No Sea), **GeoJSON**, from [data.gov.sg](https://data.gov.sg/)\n- Pre-Schools Location, **GeoJSON**, from [data.gov.sg](https://data.gov.sg/)\n- Cycling Path Network, **GeoJSON**, from [data.gov.sg](https://data.gov.sg/)\n- Latest version of Singapore Airbnb listing data, **CSV**, from [Inside Airbnb](http://insideairbnb.com/get-the-data.html)\n\n## 2.1 Folder structure\n\nInside `Hands-on_Ex01`, I created a `data` sub-folder, and within it two further sub-folders named `geospatial` and `aspatial`.\n\nThe three GeoJSON files were placed directly into `geospatial` and `listings.csv` was placed into `aspatial`.\n\n```         \nHands-on_Ex01/\n└── data/\n    ├── geospatial/\n    │   ├── MasterPlan2014SubzoneBoundaryNoSea.geojson\n    │   ├── PreSchoolsLocation.geojson\n    │   └── CyclingPathNetworkGEOJSON.geojson\n    └── aspatial/\n        └── listings.csv\n```\n\n# 3. Getting Started\n\nTwo R packages are used in this exercise:\n\n- **sf** for importing, managing, and processing geospatial data, and\n- **tidyverse** for performing data science tasks such as importing, wrangling and visualising data.\n\n::: callout-note\nTidyverse is a family of R packages. The ones I actually rely on here are **readr** for importing csv data, **tidyr** for manipulating data, **dplyr** for transforming data, and **ggplot2** for visualising data.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tidyverse)\n```\n:::\n\n\nThe [`p_load()`](https://cran.r-project.org/web/packages/pacman/pacman.pdf) function of the [**pacman**](https://github.com/trinker/pacman) package installs and loads sf and tidyverse into the R environment in a single call. That is why it is preferred over `install.packages()` followed by `library()`.\n\n# 4. Importing Geospatial Data\n\nIn this section I imported the following geospatial data into R by using [`st_read()`](https://r-spatial.github.io/sf/reference/st_read.html) of the **sf** package:\n\n- `MasterPlan2014SubzoneBoundaryNoSea`, a polygon feature layer in GeoJSON format,\n- `CyclingPathNetworkGEOJSON`, a line feature layer in GeoJSON format, and\n- `PreSchoolsLocation`, a point feature layer in GeoJSON format.\n\n::: callout-note\nEvery layer here is a single self-contained file, so the import uses one path argument rather than the `dsn` / `layer` pair the reference material uses for its shapefile. `st_read()` auto-detects the driver (shapefile, KML, GeoJSON, and so on) from the file itself.\n:::\n\n## 4.1 Importing the subzone boundary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz <- st_read(\"data/geospatial/MasterPlan2014SubzoneBoundaryNoSea.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_NO_SEA_PL' from data source \n  `/Users/norhendra/norhendra/ISSS626-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial/MasterPlan2014SubzoneBoundaryNoSea.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 323 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nThe message reveals 323 polygon features, matching the 2014 subzone count reported in the reference material. Unlike the shapefile version, the coordinate reference system reads as **WGS84 (EPSG:4326)** straight away, with a bounding box in decimal degrees rather than the tens of thousands of metres a projected layer would show. GeoJSON coordinates are always geographic per the format spec, regardless of what CRS the source data was originally surveyed in.\n\n## 4.2 Importing the cycling path network\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncyclingpath <- st_read(\"data/geospatial/CyclingPathNetworkGEOJSON.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CYCLINGPATH' from data source \n  `/Users/norhendra/norhendra/ISSS626-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial/CyclingPathNetworkGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 8523 features and 6 fields\nGeometry type: MULTILINESTRING\nDimension:     XY\nBounding box:  xmin: 103.637 ymin: 1.265428 xmax: 103.9664 ymax: 1.467361\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nThis layer has 8,523 line features and 6 attribute fields. That is noticeably more paths than the 4,651 the reference material describes, since LTA's published cycling path network has been extended since the book was written. It also carries far fewer attribute columns than the reference material's 19-field shapefile version (`OBJECTID_1`, `CYL_PATH`, `AGENCY_MAINT`, `INC_CRC`, `FMEL_UPD_D`, `SHAPE_1.LEN`). None of those extra shapefile fields are actually used later in this exercise though, so it has no effect on the analysis.\n\n::: callout-important\n## Correction to the reference material\n\nThe reference chapter describes the cycling path layer as being similar to \"the *MP19_SUBZONE_WEB_PL* shape file.\" That is a typo carried over from the book. The subzone layer imported in Section 4.1 is Master Plan **2014**, not MP19. This matters because Hands-on Exercise 2 genuinely does use the Master Plan **2019** boundary, and mixing the two up invites confusion about which vintage of subzone boundary is actually in play.\n:::\n\n## 4.3 Importing pre-school locations\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool <- st_read(\"data/geospatial/PreSchoolsLocation.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PreSchoolsLocation' from data source \n  `/Users/norhendra/norhendra/ISSS626-GAA/Hands-on_Ex/Hands-on_Ex01/data/geospatial/PreSchoolsLocation.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nThe message reveals 2,290 point features and only 2 fields, `Name` and `Description`. This actually matches the reference material's own KML import, since this GeoJSON was clearly exported directly from the original KML without flattening its attribute table. `Description` still holds an HTML table with `CENTRE_NAME`, `CENTRE_CODE`, and update-date fields embedded as markup rather than as proper columns. I don't need those attribute values for this exercise, so I leave the field as is here. The equivalent parsing step is covered properly in Hands-on Exercise 2, where the attributes are actually used.\n\n::: callout-important\n## Correction to the reference material\n\nThe reference chapter imports the pre-school layer and transforms it in the same step:\n\n``` r\npreschool = st_read(\"chap01/data/geospatial/PreSchoolsLocation.kml\") %>%\n  st_transform(crs = 3414)\n```\n\nI deliberately do **not** do this. Applying `st_transform()` at import time undermines the book's own later narrative. Its Section 1.6 explains that the preschool points \"failed to plot on top of the mpsz layer\" due to a CRS mismatch, and its Section 1.7.2 claims the printout still \"reveals wgs84 coordinate system.\" But if the transform already ran at import, neither of those statements would be true, and the book's own before and after printouts for that section are identical to each other. I import without transforming, and apply the transform later in Section 7, where it belongs.\n:::\n\n# 5. Checking the Content of A Simple Feature Data Frame\n\nBefore wrangling geospatial data, it is good practice to get to know the data set first.\n\n## 5.1 Working with `st_geometry()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 323 features \nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n\nThis displays the geometry type, the geographic extent, and the coordinate system, which is WGS84 for the reasons noted in Section 4.1.\n\n## 5.2 Working with `glimpse()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 323\nColumns: 14\n$ OBJECTID_1   <int> 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 3…\n$ SUBZONE_NO   <int> 2, 2, 3, 4, 5, 4, 10, 12, 4, 6, 1, 1, 3, 8, 3, 7, 9, 2, 1…\n$ SUBZONE_N    <chr> \"PEOPLE'S PARK\", \"BUKIT MERAH\", \"CHINATOWN\", \"PHILLIP\", \"…\n$ SUBZONE_C    <chr> \"OTSZ02\", \"BMSZ02\", \"OTSZ03\", \"DTSZ04\", \"DTSZ05\", \"OTSZ04…\n$ CA_IND       <chr> \"Y\", \"N\", \"Y\", \"Y\", \"Y\", \"Y\", \"N\", \"Y\", \"N\", \"Y\", \"Y\", \"Y…\n$ PLN_AREA_N   <chr> \"OUTRAM\", \"BUKIT MERAH\", \"OUTRAM\", \"DOWNTOWN CORE\", \"DOWN…\n$ PLN_AREA_C   <chr> \"OT\", \"BM\", \"OT\", \"DT\", \"DT\", \"OT\", \"BM\", \"DT\", \"BM\", \"DT…\n$ REGION_N     <chr> \"CENTRAL REGION\", \"CENTRAL REGION\", \"CENTRAL REGION\", \"CE…\n$ REGION_C     <chr> \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR…\n$ INC_CRC      <chr> \"B4120D23006C932A\", \"1C51019439A68700\", \"0FF1661344C84AED…\n$ FMEL_UPD_D   <chr> \"20160511160621\", \"20160511160621\", \"20160511160621\", \"20…\n$ SHAPE_1.AREA <dbl> 93140.44, 411722.82, 587222.68, 39437.94, 188767.49, 1330…\n$ SHAPE_1.LEN  <dbl> 1822.1927, 3074.9632, 4297.5999, 871.5549, 1872.7522, 160…\n$ geometry     <MULTIPOLYGON [°]> MULTIPOLYGON (((103.8432 1...., MULTIPOLYGON…\n```\n\n\n:::\n:::\n\n\nThe field names in this GeoJSON differ from the reference material's shapefile in a couple of ways worth flagging.\n\n::: callout-note\n## Correction to the reference material\n\nThe reference chapter describes area and length fields as `SHAPE_L` and `SHAPE_AREA`, and elsewhere as `SHAPE_Leng` / `SHAPE_Area`. Neither matches what's actually in this file. The GeoJSON export names them `SHAPE_1.LEN` and `SHAPE_1.AREA`, and there is no `X_ADDR` / `Y_ADDR` pair at all (those were shapefile-specific centroid columns that didn't carry over into the GeoJSON export). None of these fields are used in the calculations later in this exercise, since I derive area independently with `st_area()` in Section 9, so the mismatch doesn't affect the analysis. It would still break any code copied verbatim from the reference material that references these columns by name.\n:::\n\n## 5.3 Working with `head()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mpsz, n = 5)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 5 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.8131 ymin: 1.274155 xmax: 103.8532 ymax: 1.286506\nGeodetic CRS:  WGS 84\n  OBJECTID_1 SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND    PLN_AREA_N PLN_AREA_C\n1         21          2 PEOPLE'S PARK    OTSZ02      Y        OUTRAM         OT\n2         22          2   BUKIT MERAH    BMSZ02      N   BUKIT MERAH         BM\n3         23          3     CHINATOWN    OTSZ03      Y        OUTRAM         OT\n4         24          4       PHILLIP    DTSZ04      Y DOWNTOWN CORE         DT\n5         25          5 RAFFLES PLACE    DTSZ05      Y DOWNTOWN CORE         DT\n        REGION_N REGION_C          INC_CRC     FMEL_UPD_D SHAPE_1.AREA\n1 CENTRAL REGION       CR B4120D23006C932A 20160511160621     93140.44\n2 CENTRAL REGION       CR 1C51019439A68700 20160511160621    411722.82\n3 CENTRAL REGION       CR 0FF1661344C84AED 20160511160621    587222.68\n4 CENTRAL REGION       CR 615D4EDDEF809F8E 20160511160621     39437.94\n5 CENTRAL REGION       CR 72107B11807074F4 20160511160621    188767.49\n  SHAPE_1.LEN                       geometry\n1   1822.1927 MULTIPOLYGON (((103.8432 1....\n2   3074.9632 MULTIPOLYGON (((103.8221 1....\n3   4297.5999 MULTIPOLYGON (((103.8438 1....\n4    871.5549 MULTIPOLYGON (((103.8496 1....\n5   1872.7522 MULTIPOLYGON (((103.8525 1....\n```\n\n\n:::\n:::\n\n\n# 6. Plotting the Geospatial Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mpsz[\"PLN_AREA_N\"])\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n::: callout-tip\n`plot()` is appropriate for a quick look at a geospatial object. For high cartographic quality maps, a package such as **tmap** should be used, which is exactly what Hands-on Exercise 2 covers.\n:::\n\nNow let me try plotting the preschool layer on top of the mpsz layer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz))\nplot(st_geometry(preschool), \n     add = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n::: callout-important\n## Where this diverges from the reference material\n\nIn the reference material, this exact overlay fails, because its `mpsz` is a shapefile already in SVY21 (coordinates in metres) while `preschool` is a KML in WGS84 (coordinates in degrees). Plotting the two together puts the preschool points far outside the subzone boundaries' plotting extent.\n\nThat failure doesn't reproduce here. **Both layers are GeoJSON, and GeoJSON is always WGS84 by specification.** There is no coordinate system mismatch to cause a visible failure, so the overlay above already looks correct. This is a genuine consequence of the different file formats, not something I fixed on purpose.\n\nIt does **not** mean the projection step in Section 7 is unnecessary though. WGS84 stores angular degrees, not metres. Any calculation that assumes metric units, such as a 5 metre buffer or an area in square kilometres, will silently misinterpret those degrees as metres unless the data is first transformed to a projected coordinate system. The visual overlay working is not the same thing as the data being fit for measurement.\n:::\n\n# 7. Working with Projection\n\nMap projection is an important property of geospatial data. To perform geoprocessing that involves distance or area (buffering, area calculation), the data must be in a projected coordinate system with metric units, regardless of whether the layers visually align in WGS84.\n\n::: callout-note\n## Why this matters, from the lesson slides\n\nGeographic coordinate systems (GCS) such as wgs84 define locations on a three-dimensional spherical surface and give accurate positional information, but they are **not appropriate for distance and area measurements**. One degree at the north pole spans a far shorter ground distance than one degree at the equator.\n\nProjected coordinate systems (PCS) such as svy21 provide consistent length and area measurement across space. This is exactly why a transformation from GCS to PCS is required before any of the buffering, area, or density calculations in Section 9.\n:::\n\n## 7.1 Checking the coordinate reference system\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n:::\n\n\nThis correctly reports EPSG:4326 (WGS84).\n\n::: callout-note\n## Why the reference material's EPSG-9001 problem doesn't appear here\n\nThe reference chapter spends a subsection fixing a *wrongly labelled* CRS. Its shapefile's `.prj` file is incomplete, so `st_crs()` reports EPSG **9001**, which isn't even a coordinate system (it's the EPSG code for the unit *metre*), instead of the correct 3414. The fix there is `st_set_crs()`, which relabels metadata without moving any coordinates.\n\nThat specific failure mode is a shapefile artefact. `.prj` files are a separate sidecar file that's easy to omit or corrupt during a shapefile export. GeoJSON has no equivalent sidecar to go missing. The CRS is either implied as WGS84 by the format spec (as here) or stated explicitly inside the file itself. So there is no mislabelled CRS bug to fix in this data, and `st_set_crs()` isn't the right tool here since my CRS label is already correct. What I need instead is a genuine coordinate transformation, covered next.\n:::\n\n## 7.2 Transforming the geospatial layers to svy21\n\nSince all three geospatial layers came in as WGS84, all three need `st_transform()` before any metric geoprocessing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz3414 <- st_transform(mpsz, crs = 3414)\npreschool3414 <- st_transform(preschool, crs = 3414)\ncyclingpath3414 <- st_transform(cyclingpath, crs = 3414)\n```\n:::\n\n\n::: callout-note\nIn practice, the appropriate projected coordinate system must be identified *before* performing the transformation. [epsg.io](https://epsg.io/) provides a comprehensive list of country coordinate systems. [3414](https://epsg.io/3414) is Singapore's SVY21.\n:::\n\nConfirming the transformation took effect. The bounding box should now be in the tens of thousands, not single digits:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry(mpsz3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 323 features \nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry(preschool3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 2290 features \nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 11810.03 ymin: 25596.33 xmax: 45404.24 ymax: 49300.88\nz_range:       zmin: 0 zmax: 0\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n\nThis is the point where the projection actually starts to matter for this exercise, even though the plots in Section 6 looked fine without it. Everything from here on, including Section 9's buffers and areas, depends on these transformed versions rather than the originals.\n\n# 8. Importing and Converting Aspatial Data\n\nIn practice it is not unusual to come across data such as the Inside Airbnb `listings` file. This is called **aspatial data** because it is not geospatial data, but among its data fields there are two that capture the x and y coordinates of the data points.\n\n## 8.1 Importing the aspatial data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlistings <- read_csv(\"data/aspatial/listings.csv\")\n```\n:::\n\n\n::: callout-important\n## Correction to the reference material\n\nThe reference chapter states that \"listing tibble data frame consists of 4252 rows and 16 columns,\" while its own printed output directly above that sentence shows a different figure again. Inside Airbnb republishes its listings quarterly, so the exact row and column count will keep shifting for anyone downloading it fresh. My own file has yet another column count, since it happens to include a `host_profile_id` field the reference material's copy did not. This is exactly why I read the dimensions off the object programmatically instead of quoting a number from the book:\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(listings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3247   19\n```\n\n\n:::\n:::\n\n\nThe two fields I need for the next step are `latitude` and `longitude`, in decimal degree format, so as with the geospatial layers this is wgs84.\n\n## 8.2 Creating a simple feature data frame from an aspatial data frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlistings_sf <- st_as_sf(listings, \n                        coords = c(\"longitude\", \"latitude\"),\n                        crs = 4326) %>%\n  st_transform(crs = 3414)\n```\n:::\n\n\nThings to learn from the arguments above:\n\n- the `coords` argument requires the column name of the x-coordinates **first**, then the column name of the y-coordinates. Reversing them is a silent error since the points will still be created, just in entirely the wrong places.\n- the `crs` argument requires the coordinate system in EPSG format. [EPSG:4326](https://epsg.io/4326) is the wgs84 Geographic Coordinate System and [EPSG:3414](https://epsg.io/3414) is the Singapore SVY21 Projected Coordinate System.\n- `%>%` nests `st_transform()` so the result is immediately in the svy21 projected coordinate system, consistent with the geospatial layers transformed in Section 7.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(listings_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,247\nColumns: 18\n$ id                             <dbl> 71609, 71896, 71903, 294281, 344803, 36…\n$ name                           <chr> \"Ensuite Room (Room 1 & 2) near EXPO\", …\n$ host_id                        <dbl> 367042, 367042, 367042, 1521514, 367042…\n$ host_profile_id                <dbl> 1.462517e+18, 1.462517e+18, 1.462517e+1…\n$ host_name                      <chr> \"Belinda\", \"Belinda\", \"Belinda\", \"Elizb…\n$ neighbourhood_group            <chr> \"East Region\", \"East Region\", \"East Reg…\n$ neighbourhood                  <chr> \"Tampines\", \"Tampines\", \"Tampines\", \"Ne…\n$ room_type                      <chr> \"Private room\", \"Private room\", \"Privat…\n$ price                          <dbl> NA, NA, NA, 32, 15, NA, 26, 11, 28, 48,…\n$ minimum_nights                 <dbl> 92, 92, 92, 92, 92, 92, 92, 92, 92, 92,…\n$ number_of_reviews              <dbl> 19, 24, 46, 131, 60, 81, 163, 20, 0, 17…\n$ last_review                    <date> 2020-01-17, 2019-10-13, 2020-01-09, 20…\n$ reviews_per_month              <dbl> 0.11, 0.13, 0.25, 0.75, 0.34, 0.52, 0.9…\n$ calculated_host_listings_count <dbl> 5, 5, 5, 7, 5, 7, 7, 4, 2, 1, 8, 1, 73,…\n$ availability_365               <dbl> 90, 90, 90, 364, 364, 364, 364, 364, 36…\n$ number_of_reviews_ltm          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ license                        <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ geometry                       <POINT [m]> POINT (41972.5 36390.05), POINT (…\n```\n\n\n:::\n:::\n\n\nPlotting `listings_sf` on top of `mpsz3414`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz3414))\nplot(st_geometry(listings_sf), \n     add = TRUE, \n     pch = 20, \n     cex = 0.3, \n     col = \"steelblue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n# 9. Geoprocessing with sf package\n\nBeyond handling geospatial data (importing, exporting, assigning projections, transforming projections), the **sf** package also offers a wide range of geoprocessing (GIS analysis) functions.\n\n::: callout-note\n## Grounding this in the OGC standard\n\nFrom the lesson slides, the OGC OpenGIS Implementation Standard / ISO 19125 defines methods that support spatial analysis, including `distance`, `buffer`, `convex hull`, `intersection`, `union`, `difference` and `symmetric difference`, all of which return new geometric objects. The sf functions used below are R's implementation of exactly that standard, which is why the same verbs show up in PostGIS and QGIS.\n:::\n\n## 9.1 Use case 1: Land acquisition analysis\n\n### 9.1.1 The scenario\n\nThe authority is planning to upgrade the existing cycling path. To do so, they need to acquire 5 metres of reserved land on both sides of the existing cycling path. I am tasked to determine the extent of the land needing to be acquired and its total area.\n\n### 9.1.2 The solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_cycling <- st_buffer(cyclingpath3414, \n                            dist = 5, \n                            nQuadSegs = 30)\n```\n:::\n\n\n::: callout-note\n`dist = 5` is interpreted in the units of the layer's CRS. Because `cyclingpath3414` has already been transformed to svy21 (metres), this correctly produces a 5 metre buffer. Had I skipped Section 7.2 and buffered the original wgs84 `cyclingpath` instead, `dist = 5` would have been read as 5 **degrees**, roughly 550 km. That is exactly why the transform in Section 7 matters regardless of the overlay in Section 6 having looked fine.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_cycling <- buffer_cycling %>%\n  mutate(AREA = st_area(geometry))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(buffer_cycling$AREA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4989654 [m^2]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_selected <- mpsz3414 %>%\n  filter(SUBZONE_N == \"TAMPINES WEST\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_cycling_selected <- st_intersection(buffer_cycling, \n                                           mpsz_selected)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz_selected))\nplot(st_geometry(buffer_cycling_selected), \n     col = \"#C1443C\", \n     border = NA, \n     add = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n## 9.2 Use case 2: Number of pre-schools by planning subzone\n\n### 9.2.1 The scenario\n\nThe authority requires a count of pre-schools for each planning subzone to support forward planning.\n\n### 9.2.2 The solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz3414$`PreSch Count` <- lengths(st_intersects(mpsz3414, preschool3414))\n```\n:::\n\n\n::: callout-warning\n`st_intersects()` should not be confused with [`st_intersection()`](https://r-spatial.github.io/sf/reference/geos_binary_ops.html). The former is a **predicate** returning which features touch or overlap. The latter is a **geometry-generating operator** returning new clipped geometries.\n\nNote also that the reference chapter uses `lengths()` here (plural, the vectorised form) while its surrounding prose describes it as `length()` (singular). Only `lengths()` produces a per-subzone count.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mpsz3414$`PreSch Count`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    0.00    4.00    7.09   10.00   72.00 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_n(mpsz3414, 1, `PreSch Count`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 14 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 39655.33 ymin: 35966 xmax: 42940.57 ymax: 38622.37\nProjected CRS: SVY21 / Singapore TM\n  OBJECTID_1 SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND PLN_AREA_N PLN_AREA_C\n1        204          2 TAMPINES EAST    TMSZ02      N   TAMPINES         TM\n     REGION_N REGION_C          INC_CRC     FMEL_UPD_D SHAPE_1.AREA SHAPE_1.LEN\n1 EAST REGION       ER 21658EAAF84F4D8D 20160511160621      4339824    10180.62\n                        geometry PreSch Count\n1 MULTIPOLYGON (((42196.76 38...           72\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz3414 <- mpsz3414 %>%\n  mutate(Area = st_area(geometry))\n```\n:::\n\n\n::: callout-note\nThe reference chapter writes this as `mpsz$Area <- mpsz %>% st_area()`, mixing base assignment with a pipe. I use the tidier `mutate()` form instead, consistent with how `AREA` was computed in Section 9.1.2.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz3414 <- mpsz3414 %>%\n  mutate(`PreSch Density` = `PreSch Count` / Area * 1000000)\n```\n:::\n\n\nThe multiplier of 1,000,000 converts from counts per square metre to counts per square kilometre, since `st_area()` returns metres squared for an svy21 layer.\n\n## 9.3 Exploratory Data Analysis\n\n::: panel-tabset\n## R Graphics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(mpsz3414$`PreSch Density`)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n## ggplot2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mpsz3414, \n       aes(x = as.numeric(`PreSch Density`))) +\n  geom_histogram(bins = 20, \n                 color = \"black\", \n                 fill = \"light blue\") +\n  labs(title = \"Are pre-schools evenly distributed in Singapore?\",\n       x = \"Pre-school density (per km sq)\",\n       y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mpsz3414, \n       aes(y = `PreSch Count`, \n           x = as.numeric(`PreSch Density`))) +\n  geom_point(color = \"black\") +\n  xlim(0, 40) +\n  ylim(0, 40) +\n  labs(title = \"Relationship between pre-school density and count\",\n       x = \"Pre-school density (per km sq)\",\n       y = \"Pre-school count\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n::: callout-important\n## Correction to the reference material\n\nThe reference chapter writes this scatterplot with `geom_point(color=\"black\", fill=\"light blue\")`. `fill` has no effect here since `geom_point()` defaults to shape 19, a solid circle with no fill aesthetic, only `colour`. To actually use both, a fillable shape (21 to 25) is needed, demonstrated in the Extras.\n:::\n\n# 10. Extras\n\n## 10.1 Fixing the scatterplot properly with a fillable shape\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mpsz3414, \n       aes(y = `PreSch Count`, \n           x = as.numeric(`PreSch Density`))) +\n  geom_point(shape = 21, \n             colour = \"#1E3A5F\", \n             fill = \"#7FB3D5\", \n             size = 2.5, \n             alpha = 0.8) +\n  xlim(0, 40) +\n  ylim(0, 40) +\n  labs(title = \"Pre-school density against count, by planning subzone\",\n       x = \"Pre-school density (per km sq)\",\n       y = \"Pre-school count\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n## 10.2 Geometry validity checks before geoprocessing\n\nGeoJSON exports from open-data portals are somewhat more prone to invalid or duplicate-vertex geometries than curated shapefiles, so this check is worth running here specifically.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(st_is_valid(mpsz3414))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n    9   314 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz3414 <- st_make_valid(mpsz3414)\ntable(st_is_valid(mpsz3414))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTRUE \n 323 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(st_is_empty(mpsz3414))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n## 10.3 Choosing the right spatial predicate\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_intersects <- lengths(st_intersects(mpsz3414, preschool3414))\ncount_contains <- lengths(st_contains(mpsz3414, preschool3414))\n\ntibble(\n  predicate = c(\"st_intersects\", \"st_contains\"),\n  total_counted = c(sum(count_intersects), sum(count_contains)),\n  actual_preschools = nrow(preschool3414)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  predicate     total_counted actual_preschools\n  <chr>                 <int>             <int>\n1 st_intersects          2290              2290\n2 st_contains            2290              2290\n```\n\n\n:::\n:::\n\n\nIf `st_intersects` totals more than the actual number of pre-schools, boundary points are being double counted between adjacent subzones.\n\n## 10.4 Nearest-neighbour distance: how far is the nearest pre-school?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnearest_idx <- st_nearest_feature(listings_sf, preschool3414)\n\nlistings_sf <- listings_sf %>%\n  mutate(dist_to_preschool = st_distance(listings_sf, \n                                         preschool3414[nearest_idx, ], \n                                         by_element = TRUE))\n\nsummary(as.numeric(listings_sf$dist_to_preschool))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n   2.781  116.824  177.282  205.953  262.881 5929.910 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = listings_sf,\n       aes(x = as.numeric(dist_to_preschool))) +\n  geom_histogram(bins = 40, \n                 fill = \"#4A7C59\", \n                 colour = \"white\") +\n  labs(title = \"Distance from each Airbnb listing to its nearest pre-school\",\n       x = \"Distance (metres)\",\n       y = \"Number of listings\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n## 10.5 A quick look at region-level aggregation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_region <- mpsz3414 %>%\n  group_by(REGION_N) %>%\n  summarise(`PreSch Count` = sum(`PreSch Count`),\n            Area = sum(Area)) %>%\n  mutate(`PreSch Density` = `PreSch Count` / Area * 1000000)\n\nmpsz_region %>%\n  st_drop_geometry() %>%\n  arrange(desc(`PreSch Density`))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  REGION_N          `PreSch Count`       Area `PreSch Density`\n  <chr>                      <int>      [m^2]          [1/m^2]\n1 CENTRAL REGION               692 136405634.             5.07\n2 NORTH-EAST REGION            467 136053572.             3.43\n3 EAST REGION                  380 112969680.             3.36\n4 NORTH REGION                 303 139405603.             2.17\n5 WEST REGION                  448 257110297.             1.74\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mpsz_region[\"PreSch Count\"], \n     main = \"Pre-school count by region\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex01A_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n",
    "supporting": [
      "Hands-on_Ex01A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}